project:
  type: website
  resources: 
    - images/
  preview: 
    watch-inputs: true
    browser: false
    port: 6997


website:
  title: "Complexity Evaluation"
  search: false
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



